#!/bin/ash -x

BASE_DIR="/usr/local/mc/serv"

chmod 755 -R "${BASE_DIR}"
cd "${BASE_DIR}"

if [ ! -f "${BASE_DIR}"/eula.txt ]; then
	java -jar /run/forge.jar --installServ
	echo eula=true > eula.txt
fi

if [ ${#} == 0 ]; then
	/usr/bin/tmux new -d -s MC_SERV java -jar /usr/local/mc/serv/forge-1.12.2-14.23.5.2860.jar
	while :; do sleep 60; echo ping; done
else
	exec ${@}
fi
